// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	int user_Number = Integer.parseInt(args[0]);
	int count = 0;
	double overHalf = 0;
	double underEvenHalf = 0;
	while (count < (user_Number + 1)) {
		double randomNumber = Math.random();
		if (randomNumber > 0.5) {
			overHalf = overHalf + 1;
		} else { underEvenHalf = underEvenHalf + 1;
		}
		count = count + 1;
	}
	if (underEvenHalf != 0) {
		double ratio = overHalf / underEvenHalf;

	System.out.println("> 0.5:  " + (int)overHalf + " times");
	System.out.println("<= 0.5:  " + (int)underEvenHalf + " times");
	System.out.println("Ratio:  " + ratio);

	} else {
	System.out.println("> 0.5:  " + (int)overHalf + " times");
	System.out.println("<= 0.5:  " + (int)underEvenHalf + " times");
	}
	}

}
